version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
  open-pull-requests-limit: 10
  assignees:
  - tivac
  ignore:
  - dependency-name: jest-serializer-html
    versions:
    - ">= 7.0.a, < 7.1"
  - dependency-name: rollup
    versions:
    - 2.40.0
  - dependency-name: svelte
    versions:
    - 3.32.1
