name: Tests

on: [ push ]

jobs:
  test:
    name: node@${{ matrix.node_version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node_version: [ 14, 16 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Install node@${{ matrix.node_version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm test -- --ci --verbose

    # Run codecov after all builds, and only on a single environment
    - name: Gather Coverage
      if: matrix.os == 'ubuntu-latest' && matrix.node_version == '12'
      run: npm test -- --ci --coverage

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      if: matrix.os == 'ubuntu-latest' && matrix.node_version == '12'
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/coverage-final.json


